data:
  name: '1d-0000'
  total_num: 20003
  n_train: 16000
  n_valid: 4000
  n_test: 3
  nx: 200
  nt: 8
  sub: 1
  sub_t: 1

  savefig_path: '1d/figures/'
model:
  layers: [64,64,64,64,64]
  modes1: [8,16,16,32]
  modes2:  [4,4,4,4]
  fc_dim: 128
  in_dim: 6
  out_dim: 2
  activation: gelu

train:
  batchsize: 10
  epochs: 80
  milestones: [20,40,60]
  base_lr: 0.001
  scheduler_gamma: 0.5
  ic_loss: 5.0
  f_loss: 1.0
  xy_loss: 5.0
  h_loss: 4.0
  u_loss: 1.0
  save_dir: '1d'
  save_name: '1d-0000.pt'
  ckpt: 'checkpoints/1d/1d-0000.pt'
  ckpt_freq: 25

valid:
  batchsize: 1

test:
  batchsize: 1
  ckpt: 'checkpoints/1d/1d-0000.pt'
